# .github/workflows/firebase-deploy.yml
name: Deploy Firebase Rules

on:
  push:
    branches: [ main, master ]
    paths:
      - 'firestore.rules'
      - 'firestore.indexes.json'
      - 'firebase.json'
      - '.github/workflows/firebase-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Deploy Firestore Rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only firestore:rules --project scriptrank-5885f --token "${{ secrets.FIREBASE_TOKEN }}"
